In [ ]:
#Создать массив 10x10 со случайными значениями, найти минимум и максимум
import numpy as np


array = np.random.randint(0, 100, size=(10, 10))
print("Исходный массив:")
print(array)

min_value = array.min()
print("\nМинимальное значение:", min_value)


max_value = array.max()
print("Максимальное значение:", max_value)

Исходный массив:
[[ 3 84 92 99 42 20 63 70 69 56]
 [28 55 38 22 82 20  2 26 72  8]
 [16 13 76 27 32 35 82 14 57 29]
 [38 76 48 22 10 43 25 31 34 94]
 [70 79 99 79 45 44 97 40 61 10]
 [69 60 49 37 17 78 86 56 10 99]
 [91 78 24 54  5 78 26 55 63 17]
 [ 4 16 73 90 51  1 60 90 87 92]
 [ 4 68 85 68 45  2 88 55 86 96]
 [66 27 13 46 63 23 40  0 88 26]]

Минимальное значение: 0
Максимальное значение: 99


In [1]:
#Создать 8x8 матрицу и заполнить её единицами и нулями в шахматном порядке
import numpy as np

N = 8

matrix = np.zeros((N, N), dtype=int)


for i in range(N):
    for j in range(N):
        if (i + j) % 2 == 0:
            matrix[i][j] = 1
        else:
            matrix[i][j] = 0

print(matrix)

[[1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]]


In [ ]:
#Дан массив из 11 элементов, поменять знак у элементов, значения которых между 3 и 8
import numpy as np


z = np.arange(11)


condition = (z >= 3) & (z <= 8)


z[condition] *= -1


print(z)

[ 0  1  2 -3 -4 -5 -6 -7 -8  9 10]


In [ ]:
#Найти среднее заначение строки матрицы и вычесть его из каждого елемента строки
import numpy as np


z = np.random.rand(5, 10)


mean_values = np.mean(z, axis=1)

mean_values_reshaped = mean_values.reshape(-1, 1)

result = z - mean_values_reshaped

print(result)

[[ 0.34466632 -0.15630212 -0.05950559 -0.04118789  0.28990109  0.15120086
  -0.05988612 -0.32241258 -0.47666222  0.33018824]
 [-0.02563852  0.32961967  0.36971904 -0.21706606 -0.14889936 -0.27908303
  -0.16339593  0.18515192 -0.25051281  0.20010509]
 [ 0.33275714  0.13689389 -0.24129116  0.47510244  0.09949086 -0.20793481
  -0.40086244 -0.4916292   0.02225997  0.27521332]
 [-0.02712264 -0.04220193  0.49000375  0.1569346  -0.37984593 -0.24470777
  -0.2921421  -0.25084987  0.04388709  0.54604479]
 [ 0.31268824 -0.46823564 -0.0958906  -0.160596    0.38645081  0.42139457
  -0.36380015  0.16623966  0.14357935 -0.34183026]]


In [ ]:
#Поменяйте 1 и 2 строки матрицы
import numpy as np


z = np.arange(25).reshape(5, 5)


z[[0, 1]] = z[[1, 0]]

print(z)

[[ 5  6  7  8  9]
 [ 0  1  2  3  4]
 [10 11 12 13 14]
 [15 16 17 18 19]
 [20 21 22 23 24]]


In [ ]:
#Дан массив 10x2 подеставлющий собой точки в декартовой системе координат, преобразовать в полярную
import numpy as np

z = np.random.random((10, 2))


r = np.sqrt(z[:, 0]**2 + z[:, 1]**2)

theta = np.arctan2(z[:, 1], z[:, 0])

polar_coordinates = np.column_stack((r, theta))

print(polar_coordinates)

[[0.98179677 1.13010399]
 [1.05496538 0.79942242]
 [1.2515515  0.79969976]
 [0.79859357 1.00819923]
 [0.89857665 0.492289  ]
 [1.0702822  1.09855622]
 [0.62141437 1.07590364]
 [1.00404497 0.25316612]
 [0.839819   1.44388213]
 [0.69105356 0.92678851]]


In [ ]:
#Заменить максимальный элемент массива на ноль
import numpy as np


z = np.random.random(10)


idx_max = np.argmax(z)


z[idx_max] = 0

print(z)

[0.88929467 0.33087398 0.85878244 0.0140317  0.         0.21093919
 0.01697503 0.25044802 0.74953474 0.88198759]


In [ ]:
#Дан массив, добавить 1 к каждому элементу с индексом, заданным в другом массиве. Добавление производиться только 1 раз
import numpy as np


z = np.ones(10)


i = np.random.randint(0, len(z), 20)


unique_indices = np.unique(i)


z[unique_indices] += 1

print(z)

[2. 2. 2. 2. 2. 2. 2. 1. 2. 2.]


In [ ]:
#Дан вектор [1, 2, 3, 4, 5], построить новый вектор с тремя нулями между каждым значением
import numpy as np


z = np.array([1, 2, 3, 4, 5])


new_z = np.repeat(z, 4)


new_z[1::4] = new_z[2::4] = new_z[3::4] = 0

print(new_z)

[1 0 0 0 2 0 0 0 3 0 0 0 4 0 0 0 5 0 0 0]


In [ ]:
#Найти ближайшее к заданному значению число в заданном массиве
import numpy as np


z = np.arange(100)


v = np.random.uniform(0, 100)


index_closest = np.abs(z-v).argmin()

closest_value = z[index_closest]

print(f"Ближайшее число к {v}: {closest_value}")

Ближайшее число к 3.9858650520891215: 4
